export type UseCase = "coding" | "writing" | "data" | "research" | "mixed";
export type ToolName = "Cursor" | "GitHub Copilot" | "Claude" | "ChatGPT" | "Anthropic API" | "OpenAI API" | "Gemini" | "Windsurf";
export type PlanPrice = { plan: string; monthly: number; perSeat: boolean; source: string; note?: string };
export const PRICING: Record<ToolName, PlanPrice[]> = {
  "Cursor": [{plan:"Hobby",monthly:0,perSeat:true,source:"https://cursor.com/pricing"},{plan:"Pro",monthly:20,perSeat:true,source:"https://cursor.com/pricing"},{plan:"Business",monthly:40,perSeat:true,source:"https://cursor.com/pricing"},{plan:"Enterprise",monthly:60,perSeat:true,source:"https://cursor.com/pricing",note:"Modeled estimate when public quote is required"}],
  "GitHub Copilot": [{plan:"Individual",monthly:10,perSeat:true,source:"https://github.com/features/copilot/plans"},{plan:"Business",monthly:19,perSeat:true,source:"https://github.com/features/copilot/plans"},{plan:"Enterprise",monthly:39,perSeat:true,source:"https://github.com/features/copilot/plans"}],
  "Claude": [{plan:"Free",monthly:0,perSeat:true,source:"https://claude.com/pricing"},{plan:"Pro",monthly:20,perSeat:true,source:"https://claude.com/pricing"},{plan:"Max",monthly:100,perSeat:true,source:"https://claude.com/pricing"},{plan:"Team",monthly:30,perSeat:true,source:"https://claude.com/pricing"},{plan:"Enterprise",monthly:60,perSeat:true,source:"https://claude.com/pricing",note:"Modeled estimate when public quote is required"},{plan:"API direct",monthly:0,perSeat:false,source:"https://platform.claude.com/docs/en/about-claude/pricing"}],
  "ChatGPT": [{plan:"Plus",monthly:20,perSeat:true,source:"https://chatgpt.com/pricing"},{plan:"Team",monthly:30,perSeat:true,source:"https://chatgpt.com/pricing"},{plan:"Enterprise",monthly:60,perSeat:true,source:"https://chatgpt.com/pricing",note:"Modeled estimate when public quote is required"},{plan:"API direct",monthly:0,perSeat:false,source:"https://openai.com/api/pricing/"}],
  "Anthropic API": [{plan:"API direct",monthly:0,perSeat:false,source:"https://platform.claude.com/docs/en/about-claude/pricing"}],
  "OpenAI API": [{plan:"API direct",monthly:0,perSeat:false,source:"https://openai.com/api/pricing/"}],
  "Gemini": [{plan:"Pro",monthly:19.99,perSeat:true,source:"https://gemini.google/subscriptions/"},{plan:"Ultra",monthly:124.99,perSeat:true,source:"https://gemini.google/subscriptions/"},{plan:"API",monthly:0,perSeat:false,source:"https://ai.google.dev/gemini-api/docs/pricing"}],
  "Windsurf": [{plan:"Free",monthly:0,perSeat:true,source:"https://windsurf.com/pricing"},{plan:"Pro",monthly:20,perSeat:true,source:"https://windsurf.com/pricing"},{plan:"Teams",monthly:40,perSeat:true,source:"https://windsurf.com/pricing"},{plan:"Enterprise",monthly:60,perSeat:true,source:"https://windsurf.com/pricing",note:"Modeled estimate when public quote is required"}]
};
export const BENCHMARKS = { coding: 90, writing: 45, data: 75, research: 55, mixed: 80 } as const;
